[project]
name = "space-invaders"
version = "0.1.0"
description = "A classic Space Invaders game implementation"
requires-python = ">=3.8"
dependencies = [
    "pygame>=2.5.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build" 